INSERT INTO LIBRARY(CITY, NUMBER, POSTAL_CODE, STREET, NAME, SURNAME, TYPE_LIB) VALUES('PARIS',5,75002,'Rue du paradis','DUPOND','Martin','Publique');
INSERT INTO LIBRARY(CITY, NUMBER, POSTAL_CODE, STREET, NAME, SURNAME, TYPE_LIB) VALUES('PARIS',25,95023,'Rue de l''enfer','DESP','victor','Universitaire');
INSERT INTO LIBRARY(CITY, NUMBER, POSTAL_CODE, STREET, NAME, SURNAME, TYPE_LIB) VALUES('PARIS',185,46523,'Rue des écoutes','SERG','Michel','Universitaire');

INSERT INTO BOOK(TITLE,AUTHOR,PAGES_NUMBERS, GENRE_LITTERAIRE, ISBN) VALUES('TestLivre1','Marcel',120,'HISTORIQUE','25-46-28');
INSERT INTO BOOK(TITLE,AUTHOR,PAGES_NUMBERS, GENRE_LITTERAIRE, ISBN) VALUES('TestLivre2','DONBY',360,'SCIENCE_FICTION','49-78-14');
INSERT INTO BOOK(TITLE,AUTHOR,PAGES_NUMBERS, GENRE_LITTERAIRE, ISBN) VALUES('TestLivre3','ESDT',156,'HISTORIQUE','46-18-39');
INSERT INTO BOOK(TITLE,AUTHOR,PAGES_NUMBERS, GENRE_LITTERAIRE, ISBN) VALUES('TestLivre4','Michellon',542,'COMICS','73-16-48');

INSERT INTO LIBRARY_BOOKS(LIBRARY_JPA_ID, BOOKS_ID) VALUES(1,1);
INSERT INTO LIBRARY_BOOKS(LIBRARY_JPA_ID, BOOKS_ID) VALUES(1,4);
INSERT INTO LIBRARY_BOOKS(LIBRARY_JPA_ID, BOOKS_ID) VALUES(2,3);
INSERT INTO LIBRARY_BOOKS(LIBRARY_JPA_ID, BOOKS_ID) VALUES(3,2);